services:
  api-gateway:
    build: WebApi/
    image: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
  
  email-service:
    build: EmailNotifications.WebApi/
    image: email-service
    ports:
      - "8081:8081"
  
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.17.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=https://elasticsearh:9200

volumes:
  elasticsearch-data:
    